# Generated by Django 4.2 on 2023-07-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_expired', models.DateTimeField()),
                ('key', models.CharField(max_length=255)),
                ('class_key', models.CharField(max_length=20)),
            ],
        ),
    ]
