# Generated by Django 4.2 on 2023-07-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='key',
            name='time_expired',
        ),
    ]
