# Generated by Django 4.2.4 on 2023-08-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("champion", "0002_infomatch_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="noti",
            field=models.CharField(max_length=255),
        ),
    ]
